name: Create and publish tagged images

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-fpm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the pixelfed ref
        id: get-pixelfed-ref
        run: echo "ref=$(cat pixelfed_ref.txt)" >> $GITHUB_OUTPUT

      - name: Checkout the corresponding pixelfed repository
        uses: actions/checkout@v3
        with:
          repository: pixelfed/pixelfed
          ref: ${{ steps.get-pixelfed-ref.outputs.ref }}
          path: pixelfed

      - name: Display the pixelfed ref
        run: cd pixelfed; git rev-parse HEAD

      - name: Apply the patches, in order
        run: cd pixelfed; for patch in "${{ github.workspace }}/patches"/*.patch; do git apply "$patch" ; done

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker metadata for pixelfed-fpm on the main branch
        id: fpm-meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-fpm
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push fpm image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: pixelfed
          file: pixelfed/Dockerfile
          build-args: |
            RUNTIME_GID=1000
            RUNTIME_UID=1000
            TARGETOS=linux
            TARGETARCH=amd64
            PHP_VERSION=8.3
            PHP_BASE_TYPE=fpm
            PHP_DEBIAN_RELEASE=bookworm
            BUILD_FRONTEND=1
          target: fpm-runtime
          push: true
          tags: ${{ steps.fpm-meta.outputs.tags }}
          labels: ${{ steps.fpm-meta.outputs.labels }}
